import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Flughafen Antalya Transfer | Start Holiday Transfer',
  description: 'Buchen Sie private Transfers vom Flughafen Antalya zu Hotels in Antalya, Alanya, Belek, Side, Kemer und anderen Resorts. Komfortable Fahrzeuge, professionelle Fahrer, feste Preise.',
  keywords: [
    'Flughafen Antalya',
    'Antalya',
    'Transfer',
    'Alanya',
    'Belek',
    'Side',
    'Kemer',
    'Antalya Flughafen',
    'Konakli',
    'Antalya Havalimani',
    'Taxi Antalya',
    'Antalya Vito',
    'Bellis Deluxe',
    'Cullinan Belek',
    'Lonicera Resort',
    'Dobradan Hotel',
    'Voyage Belek',
    'Adalya Elit',
    'Titanic Hotel',
    'Kaya Palazzo',
    'Justiniano Alanya',
    'Granada Beach',
    'My Home Hotel',
    'Quattro Beach Hotel',
    'Mall of Antalya',
    'Terracity',
    'Land of Legends',
    'Rixos Sungate',
    'Rixos Tekirova',
    'Beldibi',
    'Nirvana Cosmopolitan',
    'Dobedan World Palace',
    'Rai Premium Tekirova',
    'Güral Tekirova',
    'Bosphorus Sorgun Hotel',
    'Lusso Sorgun Hotel',
    'Gloria Serenity Hotel',
    'Gloria Golf Resort',
    'Long Beach Hotel',
    'Myhome Hotel',
    'Justiniano Club Conti',
    'Selectum Family Resort Side',
    'Aska Lara',
    'Titanic Mardan Palace',
    'Titanic Deluxe Belek',
    'Mega Saray Hotel',
    'Spice Hotel',
    'Liu Resort',
    'Tui Magic Life Jacaranda',
    'Tui Magic Life Masmavi',
    'Crystal Water World',
    'Crystal Aura Beach',
    'Barut Hemera',
    'Royal Taj Mahal',
    'Kirman Leodikya',
    'Kirman Side Marin',
    'NG Phasalis',
    'Limak Limra',
    'Daima Biz',
    'Max Royal Kemer',
    'Utopia Beach Club',
    'Transport am Flughafen Antalya Kemer',
    'Mercedes Service Antalya',
    'Transport vom Flughafen Antalya nach Side',
    'Transport vom Flughafen Antalya nach Alanya',
    'Hotelservices in Antalya',
    'Transport ins Land der Legenden',
    'Stadtrundfahrt durch Antalya',
    'Reise nach Antalya',
    'Schöne Sehenswürdigkeiten in Antalya',
    'Reise nach Antalya Fethiye',
    'Transfer vom Flughafen Antalya zum Hotel'
  ],
  alternates: {
    canonical: 'https://startholidaytransfer.com/de/uber-uns',
    languages: {
      'en': 'https://startholidaytransfer.com/en/about',
      'ru': 'https://startholidaytransfer.com/ru/o-nas',
      'tr': 'https://startholidaytransfer.com/tr/hakkimizda'
    }
  }
} 