import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Antalya Airport Transfer | Start Holiday Transfer',
  description: 'Book private transfers from Antalya Airport to hotels in Antalya, Alanya, Belek, Side, Kemer and other resorts. Comfortable vehicles, professional drivers, fixed prices.',
  keywords: [
    'Antalya',
    'Transfer',
    'Alanya',
    'Belek',
    'Side',
    'Kemer',
    'Konakli',
    'Antalya airport',
    'Antalya taxi',
    'Antalya Vito',
    'Bellis deluxe hotel',
    'Calista LUXURY hotel',
    'Dobedan World Palace',
    'Rai Premium Tekirova',
    'Güral Tekirova',
    'Cullinan Belek',
    'Lonicera Resort',
    'Dobedan hotel',
    'Voyage Belek',
    'Adalya Elit',
    'Bosphorus Sorgun hotel',
    'Lusso Sorgun hotel',
    'Titanic hotel',
    'Kaya Palazzo',
    'Justiniano Alanya',
    'Granada Beach',
    'My Home hotel',
    'Quattro Beach hotel',
    'Mall of Antalya',
    'Terracity',
    'Land of Legends',
    'Rixos Sungate',
    'Rixos Tekirova',
    'Beldibi',
    'Gloria Serenity Hotel',
    'Gloria Golf Resort',
    'Long Beach hotel',
    'Myhome hotel',
    'Justiniano Club Conti',
    'Selectum Family Resort Side',
    'Aska Lara',
    'Titanic Mardan Palace',
    'Titanic Deluxe Belek',
    'Mega Saray Hotel',
    'Spice Hotel',
    'Liu Resort',
    'Tui Magic Life Jacaranda',
    'Tui Magic Life Masmavi',
    'Crystal Water World',
    'Crystal Aura Beach',
    'Barut Hemera',
    'Nirvana Cosmopolitan',
    'Royal Taj Mahal',
    'Kirman Leodikya',
    'Kirman Side Marin',
    'NG Phasalis',
    'Limak Limra',
    'Daima Biz',
    'Max Royal Kemer',
    'Utopia Beach Club',
    'Utopia Resort and Residence',
    'Akka Antedon',
    'Antalya transfer',
    'Antalya airport',
    'Transfer Kemer',
    'Voyage Belek',
    'Selectum Family Side',
    'Lonicera Resort and Spa',
    'Litora Resort Hotel',
    'Travel Blogger',
    'Rixos Premium Tekirova',
    'Liu Resorts',
    'Transfer Belek',
    'The Land of Legends Theme Park',
    'Antalya Turkey',
    'Alanya Turkey',
    'Bosphorus Sorgun Hotel',
    'Transport Antalya airport - Kemer',
    'Transport Antalya airport - Side',
    'Transport Antalya airport - Alanya',
    'Private transfer in Antalya',
    'Private transport in Antalya',
    'Mercedes service in Antalya',
    'Service in Antalya hotels',
    'Transport in Rixos Land of Legends',
    'Service in Rixos Land of Legends',
    'Antalya city tour',
    'Antalya attractions',
    'What to do in Antalya',
    'What to see in Antalya',
    'Antalya Kemer tour',
    'Antalya airport hotel transfer',
    'Shopping transfer to Antalya shops',
    'MarkAntalya',
    'Erasta',
    'Deepo Outlet',
    'Migros'
  ],
  alternates: {
    canonical: 'https://startholidaytransfer.com/en/reviews',
    languages: {
      'ru': 'https://startholidaytransfer.com/ru/otzyvy',
      'de': 'https://startholidaytransfer.com/de/bewertungen',
      'tr': 'https://startholidaytransfer.com/tr/yorumlar'
    }
  }
} 