export const metadata = {
  title: 'Трансфер из аэропорта Анталии | Start Holiday Transfer',
  description: 'Забронируйте частный трансфер из аэропорта Анталии в Белек, Сиде, Кемер, Аланью и все отели. Простая система онлайн-бронирования с мгновенным подтверждением.',
  keywords: 'Анталия, трансфер, Алания, Белек, Сиде, Кемер, Конаклы, аэропорт Анталии, такси Анталии, Анталия Вито , Bellis deluxe hotel  , calista LUXURY hotel , Dobedan World Palace , Rai Premium Tekirova , Güral Tekirova , cullinan belek , Lonicera Resort , Dobedan  hotel , voyage Belek , adalya elit , Bosphorus Sorgun hotel , Lusso Sorgun hotel ,  titanic hotel , kaya pallazo , justiano Alanya , granada Beach , my lome hotel , quattro Beach hotel , Mall of Antalya , Terracity , Land of Legens , Rixos Sungate , Rixos tekirova , Beldibi , Gloria Serenity Hotel , Gloria Golf Resort , Long Beach hotel , Myhome hotel , Justiano club Conti , Selectum Family Resort Side , Aska Lara , Adalya Elit , Titanic Mardan Palace , Titanic Deluxe Belek , Mega Saray Hotel , Spice Hotel , Liu Resort , Tui Magic Life Jacaranda , Tui Magic Life Masmavi , Crystal Water World , Crystal Aura Beach , Barut Hemera ,Nirvana cosmopolitan  , Royal Tac Mahal , Kirman Leodaikya , Kirman Side Marin , NG Phasalis , Limak Limrq , Daima Biz , Max Royal Kemer , utopiabeachclub трансфераланья , utopiaresortandresidence akkaantedon , анталиятрансфер, antalyaairport , трансферкемер , voyagebelek selectumfamilyside , loniceraresortandspa litoreresorthotel , travelblogger rixospremiumtekirova , liuresorts трансфербелек , thelandoflegendsthemepark  анталия , аланьятурция , bosphorussorgunhotel ,  анталия турция , Транспорт Анталия аэропорт- Кемер  , Транспорт Анталия аэропорт- Сиде , Белек , Кемер , Аланья , коньяалты , Индивидуальный трансфер по Анталии , Индивидуальный транспорт в Анталии , Mercedes сервис по Анталии , Транспорт Анталия аэропорт- Сиде , Транспорт Анталия аэропорт- Аланья , Индивидуальный трансфер Анталия- Сиде , Белек , Кемер , Аланья , коньяалты , Сервис по отелям Анталии , Транспорт в Rixos Land of legends , Сервис в Rixos Land of legends , Анталия тур по городу , Анталия достопримечательности , что можно поделать в Анталии , что посмотреть в Анталии , Анталия Кемер тур , Анталия аэропорт отель трансфер , ШОПИНГ-ТРАНСФЕР ПО МАГАЗИНАМ АНТАЛИИ , МаркАнталья , Эраста ,  Молл Оф Анталья , ТерраСити , Дипо Аутлет , Мигрос',
  alternates: {
    canonical: 'https://startholidaytransfer.com/ru/glavnaya',
    languages: {
      'en': 'https://startholidaytransfer.com/en/home',
      'de': 'https://startholidaytransfer.com/de/startseite',
      'tr': 'https://startholidaytransfer.com/anasayfa'
    }
  }
} 