export const metadata = {
  title: 'Book Your Transfer | Step 3 | Start Holiday Transfer',
  description: 'Finalize your airport transfer booking in Antalya. Review your booking details and complete your reservation with secure payment options.',
  keywords: 'Antalya, transfer, Alanya, Belek, Side, Kemer, Konakli, Antalya airport, Antalya taxi, Antalya Vito, Bellis deluxe hotel, calista LUXURY hotel, Dobedan World Palace, Rai Premium Tekirova, Güral Tekirova, cullinan belek, Lonicera Resort, Dobedan hotel, voyage Belek, adalya elit, Bosphorus Sorgun hotel, Lusso Sorgun hotel, titanic hotel, kaya pallazo, justiano Alanya, granada Beach, my lome hotel, quattro Beach hotel, Mall of Antalya, Terracity, Land of Legens, Rixos Sungate, Rixos tekirova, Beldibi, Gloria Serenity Hotel, Gloria Golf Resort, Long Beach hotel , Myhome hotel , Justiano club Conti , Selectum Family Resort Side , Aska Lara , Adalya Elit , Titanic Mardan Palace , Titanic Deluxe Belek , Mega Saray Hotel , Spice Hotel , Liu Resort , Tui Magic Life Jacaranda , Tui Magic Life Masmavi , Crystal Water World , Crystal Aura Beach , Barut Hemera , Nirvana cosmopolitan , Royal Tac Mahal , Kirman Leodaikya , Kirman Side Marin , NG Phasalis , Limak Limrq , Daima Biz , Max Royal Kemer , utopiabeachclub transferalanya , utopiaresortandresidence akkaantedon , antalyatransfer, antalyaairport , transferkemer , voyagebelek selectumfamilyside , loniceraresortandspa litoreresorthotel , travelblogger rixospremiumtekirova , liuresorts transferbelek , thelandoflegendsthemepark antalya , alanyaturkey , bosphorussorgunhotel , antalya turkey , Transport Antalya airport - Kemer , Transport Antalya airport - Side , Belek , Kemer , Alanya , Konyaalti , Private transfer in Antalya , Private transport in Antalya , Mercedes service in Antalya , Transport Antalya airport - Side , Transport Antalya airport - Alanya , Private transfer Antalya - Side , Belek , Kemer , Alanya , Konyaalti , Service in Antalya hotels , Transport in Rixos Land of legends , Service in Rixos Land of legends , Antalya city tour , Antalya attractions , what to do in Antalya , what to see in Antalya , Antalya Kemer tour, Antalya airport hotel transfer, SHOPPING TRANSFER TO ANTALYA SHOPS, MarkAntalya, Erasta, Mall of Antalya, TerraCity, Deepo Outlet, Migros',
  alternates: {
    canonical: 'https://startholidaytransfer.com/en/reservation/step3',
    languages: {
      'tr': 'https://startholidaytransfer.com/rezervasyon/adim3',
      'de': 'https://startholidaytransfer.com/de/reservierung/schritt3',
      'ru': 'https://startholidaytransfer.com/ru/bronirovanie/shag3'
    }
  }
} 